from src.main.reader.reader_options import (
    CSV_OPTIONS,
    JSON_OPTIONS,
)
from src.main.reader.source_schema import (
    CUSTOMERS_SCHEMA,
    PRODUCTS_SCHEMA,
    ORDERS_SCHEMA,
)
from src.main.utils.constants import (
    CUSTOMER_FILE_NAME,
    PRODUCT_FILE_NAME,
    ORDER_FILE_NAME,
    READER_MAPPING_SCHEMA_KEY_NAME,
    READER_MAPPING_OPTIONS_KEY_NAME,
)

INPUT_FILE_TYPE_SCHEMA_OPTIONS_MAP: dict = {
    CUSTOMER_FILE_NAME: {
        READER_MAPPING_SCHEMA_KEY_NAME: CUSTOMERS_SCHEMA,
        READER_MAPPING_OPTIONS_KEY_NAME: CSV_OPTIONS
    },
    PRODUCT_FILE_NAME: {
        READER_MAPPING_SCHEMA_KEY_NAME: PRODUCTS_SCHEMA,
        READER_MAPPING_OPTIONS_KEY_NAME: CSV_OPTIONS
    },
    ORDER_FILE_NAME: {
        READER_MAPPING_SCHEMA_KEY_NAME: ORDERS_SCHEMA,
        READER_MAPPING_OPTIONS_KEY_NAME: JSON_OPTIONS
    }
}
